#!/bin/sh

# PROVIDE: hw4
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# hw4_enable (bool):    Set to "YES" to enable hw4.
#                             (default: "NO")
#
# hw4_interfaces (str): List of interfaces to bring up/down
#                             on start/stop. (eg: "wg0 wg1")
#                             (default: "")
# hw4_env (str):        Environment variables for the userspace
#                             implementation. (eg: "LOG_LEVEL=debug")

. /etc/rc.subr

name=hw4
rcvar=hw4_enable
extra_commands="restart"
# extra_commands="reload status"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
restart_cmd="${name}_restart"
# reload_cmd="${name}_reload"
# status_cmd="${name}_status"

hw4_start()
{
    # Add commands to start your web app here

    # clean raid
    rmdir /var/raid/*
    # load environment variables
    . /etc/rc.conf
    cat /etc/rc.conf
    # create raid
    for i in $(seq 0 $NUM_DISKS); do
        mkdir -p /var/raid/block-$i
    done
    rmdir /var/raid/block-$NUM_DISKS

    cd /home/Jason/System-Administration/hw4/app
    . venv/bin/activate
    cd api
    python3 -m uvicorn app:APP --reload --host 0.0.0.0 &
    echo $! > /var/run/hw4.pid
}

hw4_stop()
{
    # Add commands to stop your web app here
    if [ -f "/var/run/hw4.pid" ]; then
       kill $(cat /var/run/hw4.pid)
       rm /var/run/hw4.pid
    fi
}

hw4_restart()
{
    hw4_stop
    hw4_start
}

# hw4_reload()
# {
#         
# }

# hw4_status()
# {
#         
# }

load_rc_config $name

: ${hw4_enable="YES"}
# : ${hw4_interfaces=""}
# : ${hw4_env=""}

run_rc_command "$1"